##Descargamos TOMCAT 
FROM tomcat
##Desplegamos una aplicacion WAR en el Tomcat
COPY ./app1.war /usr/local/tomcat/webapps    
MAINTAINER Apasoft Formacion "apasoft.formacion@gmail.com"
##Exponemos el Puerto 8080
EXPOSE 8080
