apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-wordpress
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: v1
  nfs:
    path: /home/kubernetes/datos/wordpress
    server: 192.168.174.131
