apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-wordpress
  labels:
    app: wordpress
spec:
  storageClassName: v1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

