apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: contenedor1
      image: ubuntu
      command: [ "/bin/sh", "-c", "sleep 1000000" ]
      volumeMounts:
      - name: volumen-secretos
        mountPath: /tmp/datos
  volumes:
    - name: volumen-secretos
      secret:
        secretName: secreto-volumen
  restartPolicy: Never
