apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-bbdd-vol2
spec:
  storageClassName: bbdd
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/bbdd-vol2"
