##Descargamos una versión concreta de APACHE, a través del tag
FROM httpd:2.4
COPY ./web/ /usr/local/apache2/htdocs/
MAINTAINER Apasoft Formacion "apasoft.formacion@gmail.com"
##Exponemos el Puerto 80
EXPOSE 80
